### PR TITLE
Add brand new logo to the project

### PR DESCRIPTION
**Pull request by caneco**
Following your request in the tweet:
https://twitter.com/OliverNybroe/status/1180087415249223680

Here it is your brand new logo. **Hope you like it!** 😄 

image

### CODE REVIEW

**Comment by caneco** [comment]
Sorry. Tiny… tiny, fix in the logo. You can blame my OCD 😅 

image

**Comment by olivernybroe** [comment]
Thanks a lot! 
This is so awesome ❤️

I'll make a release with the new logo soon!
Do you by any chance have the svg of it also?

**Comment by caneco** [comment]
@olivernybroe SVGs on November if you don't mind :)

**Comment by olivernybroe** [comment]
@caneco Yeah sounds perfect :) 

IntelliJ plugins require svg's before they can be in the marketplace

**Pull request merged**
